// Eine Seitenleiste für alle Doku-Bereiche.
// 'autogenerated' mit dirName '.' bezieht sich jeweils auf den Ordner des
// Bereichs, in dem die Datei verwendet wird — deshalb genügt eine Datei für
// die Infoblätter und für jedes Tutorial.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
